name: Sync Production Scripts
on:
  push:
    branches:
      - main
    paths:
      - '.github/**'
      - 'install/*.ps1'
      - 'install/cluster/prod*/**'
      - 'install/cloud/**'
      - 'cluster/cloudwatch/aws-collectors/**'

jobs:
  create-pr:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2
          ssh-key: ${{ secrets.RELEASE_KEY }}

      - name: Prepare
        shell: bash
        run: |
            git config --local user.email "payara-cloud-release@payara.fish"
            git config --local user.name "Payara Cloud Release [bot]"
            # This might be incorrect change to display if the push spanned
            # multiple commits, but it's better than nothing.
            git push --force origin HEAD^:prod-scripts
            
          
      - name: Create Pull Request
        uses: actions/github-script@v7
        with:
          script: |
            const { data: existingPRs } = await github.rest.pulls.list({
              owner: context.repo.owner,
              repo: context.repo.repo,
              head: 'main',
              base: 'prod-scripts',
              state: 'open'
            });
            
            if (existingPRs.length === 0) {
              await github.rest.pulls.create({
                owner: context.repo.owner,
                repo: context.repo.repo,
                title: 'Sync production scripts from main',
                head: 'main',
                base: 'prod-scripts',
                body: `This PR was automatically created to sync production scripts with main.
                
                Changes in the following paths triggered this PR:
                - .github/
                - install/*.ps1
                - install/cluster/prod*/
                - install/cloud/
                - cluster/cloudwatch/aws-collectors/`
              });
            }